# Generated by Django 4.1.1 on 2022-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='banner',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='', upload_to='Images'),
        ),
    ]
