# Generated by Django 4.1.1 on 2022-09-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_remove_banner_is_deleted_banner_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('contents', models.TextField()),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('contents', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id_specialization_set', to='DemoApp.course')),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoApp.course')),
            ],
        ),
    ]
