# Generated by Django 4.1.1 on 2022-09-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_course_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='uni_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoApp.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
