# Generated by Django 4.1.1 on 2022-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_alter_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=''),
        ),
    ]
