# Generated by Django 4.1.1 on 2022-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0005_alter_banner_deleted_at_alter_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='deleted_at',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
